name: Keep Alive

on:
  schedule:
    - cron: '*/15 * * * *' # Runs every 15 minutes
  workflow_dispatch: # Allows manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: |
          if [ -z "${{ secrets.APP_URL }}" ]; then
            echo "APP_URL secret is not set. Skipping ping."
            exit 0
          fi
          curl -s ${{ secrets.APP_URL }}/ping
